### ISSUE TITLE
ScrollController should be inside a Stateful Widget, shouldn't it?

### ISSUE THREAD

**Issue by zsoerenm** [piedcipher/beer-app#2]
Thank you for this tutorial.
I see you have placed the `ScrollController` inside a `StatelessWidget`, but shouldn't it be a `StatefulWidget`?
Otherwise the `StateController` can not be disposed.
See here: https://stackoverflow.com/questions/55549663/do-stateless-widgets-dispose-on-their-own

Felix Angelov is also using a `StatefulWidget` for this case:
https://medium.com/flutter-community/flutter-infinite-list-tutorial-with-flutter-bloc-2fc7a272ec67

**Comment by piedcipher** [comment]
Hi @zsoerenm, I'm glad you find it useful. Thanks for opening the issue. I'll refactor to StatefulWidget.

**Comment by piedcipher** [comment]
Patched! :tada:
